# Generated by Django 2.2.3 on 2021-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('bugtype', models.CharField(default='', max_length=20)),
                ('heading', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
